### ISSUE TITLE
Provide a text box for writing in the "description" field when annotating

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/annotator_store-gem#118]
Amelia:

> Initially adding a note while coding was possible (but [not] a requirement), and now it’s gone completely – bringing this feature back would be ideal.

**Comment by tanius** [comment]
This means, re-enable the comment field of the Annotator.js overlay, allowing to add a note in addition to a tag. Since we use Annotator.js in such a way to only add one tag per annotation, each of these tags would get its own note field. This makes it possible to add a note to each annotation, which seems to be what the ethnographers want.

**Comment by tanius** [comment]
Done by @damingo by now. For now, the comment is only displayed when the annotation is in edit mode, not when mousing over an annotation to show it. But that's another issue!
