### ISSUE TITLE
Code search by words or beginning of words, not letter strings in centre of word

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#169]
Ideal if search code option shows codes with specific words/beginning of words not internal strings of letters e.g. when the typing the word "car", the search codes option returns all the words with the string "car" in them, like "aftercare" -- if searching for a shorter word, this can create too much overproliferation. Low priority.

**Comment by tanius** [comment]
This could be configurable by language? Because in more synthetic languages like German, the ways to create more specific words includes both suffixes and prefixes. For example when I search for "brot" I'd like to see proposals for "Brotkrumen" (bread crumbs) as well as "Knäckebrot" (crisp bread).

However, Google's search (as the reference for how to do auto-complete) also only suggests proposals with words starting with the strings entered, including for German search words. So probably it's best to implement it that way, as proposed by you.

**Comment by miahass** [comment]
This was requested by Wojt (it hasn’t bothered me personally) so I can ask him to come respond :)

**Comment by VooVooVoo** [comment]
Yeah, ok. Fine by me :)

**Comment by damingo** [comment]
Done. Will be deployed with the next version.
