### ISSUE TITLE
Finding the specific annotation from code view

### ISSUE THREAD

**Issue by katejsim** [edgeryders/annotator_store-gem#176]
Annotations featured in individual code page: when clicked, OE automatically displays the post including the coded annotation on top ONLY IF this post is in the first page. This means that annotations in later pages require ethnographers to click next, ctrl+F the annotation, and repeat this until the post is found.

**Comment by miahass** [comment]
@katejsim I'm having a hard time understanding this --- can you explain a) what you are trying to do and b)what you would like to happen instead? Thank you!

**Comment by katejsim** [comment]
Hey @miahass,

So, let's say I am looking at the annotations for #community building and I want to go back to the first annotation here: 
![Screen Shot 2020-08-25 at 12 30 47 PM](https://user-images.githubusercontent.com/55029800/91169308-02558800-e6cf-11ea-8efb-da0d3fb65e5b.png)

When I click on the first annotation and that annotation happens to appear on the first page of OE coding view, sometimes OE directly brings up that associated post on top. 
![Screen Shot 2020-08-25 at 12 29 57 PM](https://user-images.githubusercontent.com/55029800/91169400-3466ea00-e6cf-11ea-8ca2-99dfb7e2329b.png)

But if I want to find an annotation that occurs in the second or third page, I have to just keep clicking 'next page' and manually ctrl+F for the annotation or the code. 
![Screen Shot 2020-08-25 at 12 25 31 PM](https://user-images.githubusercontent.com/55029800/91169452-4c3e6e00-e6cf-11ea-9389-65b1c70a67f4.png)

So, ideally: when clicked on a particular annotation, it would be great if OE would show the post containing the annotation right away. 

I'm actually not even sure if OE is meant to be doing this, just noticed that it shows the post featuring the desired annotation on top IF the post is on the first page. Does this make sense? Otherwise, happy to hop on the phone to explain.

**Comment by miahass** [comment]
OK, I understand you. For clarity in future, rather than saying "OE displays x", be very deliberate in your wording about whether you mean the code view in the backend or the coding view in the frontend (and where specifically in each view you are). Pictures help, so thanks for those! This issue would be more clearly articulated as "Navigating to exact annotation on frontend by clicking on annotation from code view list in backend". Am I describing the right thing or do you mean something else? 

When you describe the issue, imagine that you are writing an exact guide of what's wrong and how you'd ideally like to see something fixed. Be as precise as possible. It doesn't help to get on the phone with me because we need to describe these to Matt and Dan as well.

**Comment by miahass** [comment]
The problem: When clicking on an annotation in the backend, you can only access that original annotation in the front end by clicking on the thread link. It at that point takes you to the thread itself rather than the specific location where the annotation was assigned. This makes recoding that selection difficult, because you have to search in the posts + comments for that particular annotation. 

![image](https://user-images.githubusercontent.com/26431602/91314850-e6c1ae80-e7ae-11ea-8662-b958acdd86c0.png)

Clicking this annotation takes you here: 

![image](https://user-images.githubusercontent.com/26431602/91314920-fd680580-e7ae-11ea-9aee-0bd5ed1d43e0.png)

At which point you have to click on the "Topic", which drops you at the beginning of the post even if that specific annotation is 10 comments down. 

Requested solution: when clicking on the annotation in the backend, annotation links straight to specific location where annotation is in the front end. Doing this at just the post or comment level is fine (e.g. takes you to the specific post or comment where this annotation is).

**Comment by damingo** [comment]
In the list of annotations there is now a link "Show in topic" below each quote. This links straight to the annotation (post) in the front end.
Note: The changes still need to be deployed.
