### ISSUE TITLE
Only See Code List from one Discourse tag, based upon User Settings, across all of Open Ethnographer (both as suggestions and in view/edit/merge code list)

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#192]
Currently, when searching for a code, people see codes from all discourse tags, and have to manually select the discourse tag of the code they are looking for. 

Instead, the user setting that a user selects should mean that they only see codes from that Discourse tag, as suggestions when coding AND in the backend when editing, merging, forking, and renaming codes. 

This will hopefully at least partially fix 2 problems: 

1. Right now, we have a problem with codes from different projects overlapping. We can't have a situation where someone in POPREBEL has used the code "destiny" and someone in NGI uses that same code to code their content, but then the POPREBEL ethnographer decides to rename the destiny code to "fate" or merge it with another code entirely. The NGI ethnographer would then lose their code. Instead, the codes from different projects need to be kept entirely separate. 

2. It is very slow and tedious to have to filter by project every time you are editing codes -- ethnographers only ever work on one project at a time and currently @miahass who is @amelia on the Edgeryders platform is the only person who is ever working on 2 projects at all. I can change my user settings when I switch.

**Comment by tanius** [comment]
We could initialize the [Codes list page](https://edgeryders.eu/annotator/codes) so that the Discourse tag filter is set to what the user has in the settings; that's basically just about adapting the "Codes" menu link in the left sidebar. And modify the search function so that it takes over the current filters when starting a search, rather then resetting them to "no filters" every time.

That will still allow to manually change the Discourse tag filter for cases where people want to see codes from all or a different Discourse tag.

That implementation outlined above is reasonably small to still fit in, so over to @damingo to do it some time in the next days.

**Comment by miahass** [comment]
Yes, that would be excellent. Thank you!

**Comment by damingo** [comment]
Done. New version will be uploaded today.
