### ISSUE TITLE
Need to Prevent Overlapping Project Codes (based upon Discourse tags)

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#193]
Right now, we have a problem with codes from different projects overlapping and being merged in one project, affecting the other project. For example, we need to protect against a situation where someone in POPREBEL has used the code "destiny" and someone in NGI uses that same code to code their content, but then the POPREBEL ethnographer decides to rename the destiny code to "fate" or merge it with another code entirely. The NGI ethnographer would then lose their code. Instead, the codes from different projects need to be kept entirely separate somehow. 

I am not sure how to approach this, but it's very important. any ideas @tanius?

**Comment by miahass** [comment]
In an ideal world, what would happen is that since users from a discourse tag have in their user settings that they only see codes from that discourse tag, no one would ever choose to use a code from another project (the way we have it now). But since I'm working on both projects, it seems like I've created a problem -- one of my codes is used in both places, and then becomes available for use in both tags, and then a merge in one ends up being a merge in both.

**Comment by tanius** [comment]
> users from a discourse tag have in their user settings that they only see codes from that discourse tag

So if we modified that user setting so that (1) everyone always has one Discourse tag selected there and (2) it is not possible to select two or more Discourse tags there … that would solve it, for the most part. There is one exception though: situations where one topic is tagged with, for example, both `ethno-ngi-forward` and `ethno-poprebel`. That could be prevented using the setting "Limit one tag per topic from this group" in a [Discourse tag group](https://edgeryders.eu/tag_groups) created for all the `ethno-*` tags. However, sometimes it may be desirable to tag one topic with two `ethno-*` Discourse tags, because it is relevant for both coding projects.

Another option would be to use [Discourse Data Explorer](https://edgeryders.eu/admin/plugins/explorer) queries to regularly check for cases of code re-use between coding projects, and fix it in time.

In total, there is no good solution. The reason is that, in the very beginning (before you joined), Open Ethnographer was meant to be a tool for crowdsourcing ethnographic annotations. So there would be one large "folk ontology" of codes, and projects are simply subsets of this common, platform-wide dataset to allow a focused analysis. The idea behind this was to make coding much more efficient by allow code re-use across projects.

So my proposal would be to rather think about how you can adapt the coding practices to make use of this data architecture, including the efficiencies of code re-use it was meant to enable. So rather than agreeing on one code ontology per team, there would have to be a platform-wide process for this.

Makes sense?

**Comment by tanius** [comment]
In other words, you're asking for something that Open Ethnographer was not built for, and adapting the complete data architecture is something we can't afford to do right now. Open Ethnographer was not meant to be a replacement for traditional QDA software, but, as the name says, to be more "open". And now we have to find ways to live with that openness :D

**Comment by miahass** [comment]
Yes, it makes sense, and I kind of knew that this is what you were going to say :D  -- it is definitely linked to a larger question about the codes themselves... and I do think openness is a good thing. I feel pretty confident that the solution implemented in the other issue (limiting the vision of ethnographers to their own project) should fix most of these issues. 

I will, I think, just need to get good at using the data explorer. Let's close this for now and I'll see if implementing solution [192](https://github.com/edgeryders/annotator_store-gem/issues/192) makes this work well enough that I can work around it to better keep the openness.

**Comment by tanius** [comment]
Had another, better idea how you can use the software if you want to avoid overlapping codes between projects:

Set up the code hierarchy so that the top level indicates the project, such as "ngi" or "poprebel". That makes it simple to ensure using only the "right" codes while coding, and even enables coding the same topic in two different coding projects without interference.

When a project is over, such codes can be re-used in other projects by moving them around in the coding hierarchy. Of course, after archiving the codes and annotations in the state used for the analysis of a specific project. I think that's the best of both worlds: a project-specific code namespace while a project is running, and the openness of code reuse afterwards.

**Comment by miahass** [comment]
I think this is a great idea in terms of the ontology. The only issue is that until we have something that makes creating hierarchies easier (https://github.com/edgeryders/annotator_store-gem/issues/4) it will be pretty tedious/time intensive to add that extra step for every code.

**Comment by tanius** [comment]
> something that makes creating hierarchies easier (#4)

I think this can be solved quite easily; see #195, which Daniel will implement soon. Because what we want here is not so much a comfortable way to edit code hierarchies of existing codes, but to create a new code on-the-fly in a specific position in the code hierarchy.
