### ISSUE TITLE
Why do the names of the same code in different languages have different IDs?

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/annotator_store-gem#196]
Not a bug but a question. What is the meaning of `ID` in the `localized tags` section of OpenEthnographer? 

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1976806/97080234-2a436800-15fa-11eb-924a-e9e18209d433.png">

(I am not sure an issue is the right place to put it, but it does not seem pertinent to coding, so I did not put it into the Opeh Ethno manual, and this repo does not have a wiki.)

**Comment by tanius** [comment]
It's not the code ID, but the code name ID. That's why they are different.

Technically, the column combination "name, path, language" could also have been used as the primary key, in which case a separate code name ID column would have been unnecessary. But I guess that "Administrate", the Rails engine Daniel used to build the Open Ethnographer backend, simply defaults to adding an ID column to every table.

Showing this column in the Open Ethnographer backend is unnecessary though. We should hide it.
