### ISSUE TITLE
Propose backend code search results in both the user's preferred language and English

### ISSUE THREAD

**Issue by ZdenekS-POPREBEL** [edgeryders/annotator_store-gem#200]
Hello,

I have found a problem with various language mutations of codes. I have Czech as a preset language. However, in the main code-view search window, I can search only in English (unless the code does have only a Czech name). When I am merging two codes, I have to search for Czech versions of the code name in the window where I search for code to be merged. Unless the code is a child; I need to search in English again if it is a child. (So it seems to me.).

Thanks for solving this. Zdenek

**Comment by tanius** [comment]
It's not yet clear to me if you're describing one or two issues, and what the steps, expected outcome and actual outcome are for each of them. I'll test some things to try and understand what this issue is about. But step-by-step instructions to reproduce an example of this issue would be appreciated to speed things up.

**Comment by ZdenekS-POPREBEL** [comment]
Dear @tanius 

so, once again, hopefully more understandable.

When I am searching for a code in my back-end, I can search only in English, if a code has both Czech and English names/labels. See the example of "education"/"vzdělávání" (in Czech). This is despite my Language in settings is set to Czech.
![search_education-cz](https://user-images.githubusercontent.com/71142609/99006738-378dab80-2543-11eb-9cae-4976f890edb3.png)
![search_education-en](https://user-images.githubusercontent.com/71142609/99006733-35c3e800-2543-11eb-950b-0e18cafd742a.png)

But, when I am merging codes, I have to search them in Czech, because if I use English, only codes that have only English names (and no Czech translations) appear. The codes, that have Czech translations won't appear.
![merge_education-cz](https://user-images.githubusercontent.com/71142609/99006735-36f51500-2543-11eb-9fc3-08f96b151a96.png)
![merge_education-en](https://user-images.githubusercontent.com/71142609/99006737-36f51500-2543-11eb-9a65-9062c1f140a7.png)

Has this cleared the bug that I am reporting?

Best, Zdeněk

**Comment by tanius** [comment]
Yes, it's clear now.

So, task for @damingo:

1. We want both the backend's code search and the backend's autocomplete widgets for codes (as used for merging codes) to show the same results.

2. In particular, results should include all code names in all available languages, regardless the user's language preferences. Currently, the backend's code search only returns results in English, and the code merge widget only returns results in the user's preferred language.

3. Technically, including results in all languages can result in the same code appearing multiple times in the search result, in different positions due to the search result sort order. That is accepted behavior. The backend's "Code" tab usually shows a list of codes but in case of search results it will show a lost of code names. That will however not confuse users, as any duplicates will not be evident (except by glimpsing on the code ID).

(Reasoning for the proposal above: identical code names in different languages are very rare. So by searching for a code name in a certain language, it is near certain that users will only see codes with names in that language – which is what they wanted. This can in a future separate different issue be improved by indicating the code name language behind every code name, wherever it appears in Open Ethnographer.)

**Comment by damingo** [comment]
Implemented and deployed.
