### ISSUE TITLE
Highlighted annotations don't appear in coding view

### ISSUE THREAD

**Issue by VooVooVoo** [edgeryders/annotator_store-gem#210]
![image](https://user-images.githubusercontent.com/20644443/120169943-bfe24e00-c200-11eb-9654-f1bd3c5f8594.png)
As you can see from the codes to the right, the text was coded properly, but the annotations are not highlighted and do not appear in the coding view. Instead, there is some real mess with just a few letters highlighted and showing some random code on them.

**Comment by damingo** [comment]
This seems to be caused by the posts being edited after they were annotated.  Re-anchoring of annotations is not yet supported but planned in #209.

**Comment by tanius** [comment]
In other words, this issue happens for the same reason that makes it impossible to automatically split annotated texts right now: when the text changes, the codings added to it become misaligned and confused.

The workflow always has to be: (1) write the Discourse post text and only then (2) code it with Open Ethnographer.

Later edits to the coded text that just consist of deleting a trailing portion of the text will not confuse existing annotations, but all other edits will and should be avoided. In the next project, we'll create a function for automated re-aligning of annotations after the base text was edited (see #209), but we can't do that now due to budget constraints.
