### ISSUE TITLE
Code ownership

### ISSUE THREAD

**Issue by VooVooVoo** [edgeryders/annotator_store-gem#211]
Once the codes have been grouped in meta categories (Z Something), every child of that category lost its original authorship, which now is attributed to the creator of the category. In other words, codes created by, say, me, having become children to a certain category, appear now to have been created by the creator of that category.

**Comment by damingo** [comment]
It turns out that the creator of a post is not changed when posts are moved, but the UI in the codes list made it look like it is. When the "Creator: __" filter is active, the "by [username]" information was no longer displayed and one assumes that all displayed codes belong to the selected creator. But the filter is only applied to the first level of the codes. Sublevels cannot be filtered by creator as in cases like this:
```
(code1) by A
    (code2) by B
        (code3) by A
```
code3 would not be displayed as its parent code2 was created by a different user.
I updated the list so that the "by [username]" is now always displayed.
